SistemaDepPessoal/Models/CadastroModel.cs
namespace SistemaDepPessoal.Models
{
    public class CadastroModel
    {
        public int Id { get; set; }

        public string Name { get; set; }
        public string Last_Name { get; set; }
        public string CPF { get; set; }
        public string Cargo { get; set; }
        public string Setor { get; set; }
        public int Idade { get; set; }
        public double Salario { get; set; }
    }
}

SistemaDepPessoal/Models/ErrorViewModel.cs
namespace SistemaDepPessoal.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SistemaDepPessoal/Controllers/CadastrosController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaDepPessoal.Models;
using SistemaDepPessoal.Repositorio;

namespace SistemaDepPessoal.Controllers
{
    public class CadastrosController : Controller
    {
        private readonly ICadastroRepositorio _cadastroRepositorio;
        public CadastrosController(ICadastroRepositorio cadastroRepositorio)
        {
            _cadastroRepositorio = cadastroRepositorio;
        }

        public IActionResult Index()
        {
            var cadastros = _cadastroRepositorio.BuscarTodos();
            return View(cadastros);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            CadastroModel cadastro = _cadastroRepositorio.ListarPorId(id);
            return View(cadastro);
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            CadastroModel cadastro = _cadastroRepositorio.ListarPorId(id);

            return View(cadastro);
        }

        [HttpGet]
        public IActionResult Apagar(int id)
        {
            _cadastroRepositorio.Apagar(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Criar(CadastroModel cadastro)
        {
            _cadastroRepositorio.Adicionar(cadastro);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Alterar(CadastroModel cadastro)
        {
            _cadastroRepositorio.Atualizar(cadastro);
            return RedirectToAction("Index");
        }
    }
}

SistemaDepPessoal/Controllers/CalculadoraController.cs
using Microsoft.AspNetCore.Mvc;

namespace SistemaDepPessoal.Controllers
{
    public class CalculadoraController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SistemaDepPessoal/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaDepPessoal.Models;
using System.Diagnostics;

namespace SistemaDepPessoal.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SistemaDepPessoal/Views/Cadastros/ApagarConfirmacao.cshtml
@model CadastroModel
@{
    ViewData["Title"] = "Confirmação apagar o funcionário";
}

<div class="text-center">
    <h3>Realmente deseja apa gar o funcionario (@Model.Name )?</h3>
</div>
<br />

<div class="text-center">
    <input class="form-check-input" type="checkbox" id="invalidCheck2" required>
    <label class="form-check-label" for="invalidCheck2">
        Confirmo que desejo excluir
    </label>
    <br />
    <br />
    <a class="btn btn-primary" role="button" asp-controller="Cadastros" asp-action="Index">Cancelar exclusão</a>
    <a class="btn btn-danger" role="button" asp-controller="Cadastros" asp-action="Apagar" asp-route-id="@Model.Id">Confirmar exclusão</a>
</div>

SistemaDepPessoal/Views/Cadastros/Criar.cshtml
@model CadastroModel
@{
    ViewData["Title"] = "Cadastro de funcionário";
}
<h1 style="text-align: center">Cadastrar novo funcionário</h1>
<div id="teste" class="text-center  col-md-12">

    <form class="row g-3" asp-controller="Cadastros" asp-action="Criar" method="post">
        <div class="col-md-3">
            <label for="validationDefault01" class="form-label">Nome</label>
            <input type="text" asp-for="Name" class="form-control" id="validationDefault01" placeholder="Fulano" required>
        </div>
        <div class="col-md-3">
            <label for="validationDefault02" class="form-label">Sobrenome</label>
            <input type="text" asp-for="Last_Name" class="form-control" id="validationDefault02" placeholder="Maximus" required>
        </div>
        <div class="col-md-3">
            <label for="validationDefault03" class="form-label">CPF</label>
            <input type="text" asp-for="CPF" class="form-control" id="validationDefault03" onkeypress="$(this).mask('000.000.000-00');" required>
        </div>
        <div class="col-md-3 form-group">
            <label for="validationDefault04" class="form-label">Cargo</label>
            <select type="text" asp-for="Cargo" class="form-control" id="validationDefault03" value="" required>
                <option>Diretor</option>
                <option>Gerente</option>
                <option>Gestor</option>
            </select>
        </div>
        <div class="col-md-3">
            <label for="validationDefault05" class="form-label">Setor</label>
            <input type="text" asp-for="Setor" class="form-control" id="validationDefault04" required>
        </div>
        <div class="col-md-3">
            <label for="validationDefault06" class="form-label">Idade</label>
            <input type="number" asp-for="Idade" class="form-control" id="validationDefault05" required>
        </div>
        <div class="col-md-3">
            <label for="validationDefault07" class="form-label">Salário</label>
            <input type="text" asp-for="Salario" class="form-control" id="validationDefault06" onkeypress="$(this).mask('0.000,00');" required>
        </div>
        <!--<div class="col-md-3">
            <label for="validationDefault7" class="form-label">Data de Inicio</label>
            <input type="text" asp-for="Data_Inicio" class="form-control" id="validationDefault7" onkeypress="$(this).mask('00/00/0000');" placeholder="11/11/2000"/>
        </div>-->
        <hr></hr> <!--Tem que concertar isso pq ta feio-->
        <div class="col-3">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" id="invalidCheck2" required>
                <label class="form-check-label" for="invalidCheck2">
                    Confirmo todos os dados
                </label>
            </div>
        </div>
        <div class="col-11">
            <button class="btn btn-primary" type="submit">Cadastrar</button>
            <a class="btn btn-danger" type="submit" asp-controller="Cadastros" asp-action="Index">Cancelar</a>
        </div>
    </form>
</div>

SistemaDepPessoal/Views/Cadastros/Editar.cshtml
@model CadastroModel
@{
    ViewData["title"] = "Editar cadastro";
}

<div class="text-center">
    <h1 class="display-4">Editar cadastro</h1>
</div>


<form class="row g-3" asp-controller="Cadastros" asp-action="Alterar" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="col-md-3">
        <label for="validationDefault01" class="form-label">Nome</label>
        <input type="text" asp-for="Name" class="form-control" id="validationDefault01" placeholder="Fulano" required>
    </div>
    <div class="col-md-3">
        <label for="validationDefault02" class="form-label">Sobrenome</label>
        <input type="text" asp-for="Last_Name" class="form-control" id="validationDefault02" placeholder="Maximus" required>
    </div>
    <div class="col-md-3">
        <label for="validationDefault03" class="form-label">CPF</label>
        <input type="text" asp-for="CPF" class="form-control" id="validationDefault03" onkeypress="$(this).mask('000.000.000-00');" required>
    </div>
    <div class="col-md-3 form-group">
        <label for="validationDefault04" class="form-label">Cargo</label>
        <select type="text" asp-for="Cargo" class="form-control" id="validationDefault03" value="" required>
            <option>Diretor</option>
            <option>Gerente</option>
            <option>Gestor</option>
        </select>
    </div>
    <div class="col-md-3">
        <label for="validationDefault05" class="form-label">Setor</label>
        <input type="text" asp-for="Setor" class="form-control" id="validationDefault04" required>
    </div>
    <div class="col-md-3">
        <label for="validationDefault06" class="form-label">Idade</label>
        <input type="number" asp-for="Idade" class="form-control" id="validationDefault05" required>
    </div>
    <div class="col-md-3">
        <label for="validationDefault07" class="form-label">Salário</label>
        <input type="text" asp-for="Salario" class="form-control" id="validationDefault06" onkeypress="$(this).mask('0.000,00');" required>
    </div>
    <!--<div class="col-md-3">
        <label for="validationDefault7" class="form-label">Data de Inicio</label>
        <input type="text" asp-for="Data_Inicio" class="form-control" id="validationDefault7" onkeypress="$(this).mask('00/00/0000');" placeholder="11/11/2000"/>
    </div>-->
    <hr></hr> <!--Tem que concertar isso pq ta feio-->
    <div class="col-3">
        <div class="form-check">
            <input class="form-check-input" type="checkbox" id="invalidCheck2" required>
            <label class="form-check-label" for="invalidCheck2">
                Confirmo todos os dados
            </label>
        </div>
    </div>
    <div class="col-11">
        <button class="btn btn-primary" type="submit">Salvar</button>
        <a class="btn btn-danger" type="submit" asp-controller="Cadastros" asp-action="Index">Cancelar</a>
    </div>
</form>

SistemaDepPessoal/Views/Cadastros/Index.cshtml
@model List<CadastroModel>
@{
    ViewData["Title"] = "Funcionários";
}

<div class="text-center">
    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" asp-controller="Cadastros" asp-action="Criar">Adicionar novo contato</a>
    </div>
    <h1 class="display-4">Funcionários</h1>
    <br />
    <table id="tabelas" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Sobrenomeo</th>
                <th>Idade</th>
                <th>CPF</th>
                <th>Salario</th>
                <th>Cargo</th>
                <th>Setor</th>
                <th>Data de Inicio</th>              
                <!--<th class="text-center">Ação</th>-->
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (CadastroModel cadastro in Model)
                {
                    <tr>
                        <td>@cadastro.Name</td>
                        <td>@cadastro.Last_Name</td>
                        <td>@cadastro.Idade</td>
                        <td>@cadastro.CPF</td>
                        <td>$@cadastro.Salario</td>
                        <td>@cadastro.Cargo</td>
                        <td>@cadastro.Setor</td> 
                        <!--<td>__/__/__</td>-->
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-route-id="@cadastro.Id" asp-controller="Cadastros" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@cadastro.Id" asp-controller="Cadastros" asp-action="ApagarConfirmacao">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>

</div>


<script type="text/javascript" src="https://cdn.datatables.net/v/bs5/dt-1.13.1/datatables.min.js"></script>

SistemaDepPessoal/Views/Calculadora/Index.cshtml
@{
    ViewData["Title"] = "Calculadora";
}
<h1>@ViewData["Title"]</h1>

<div class="text-center">
    <h1 class="display-4">Calculadora</h1>
    <p>Teste</p>
</div>

SistemaDepPessoal/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Sistema DP";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo!</h1>
    <p>Sistema de Gestão para Departamento Pessoal</p>
</div>

SistemaDepPessoal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistema DP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaDepPessoal.styles.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs5/dt-1.13.1/datatables.min.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SDP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculadora" asp-action="Index">Calculadora</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cadastros" asp-action="Index">Funcionários</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RS Soluções - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs5/dt-1.13.1/datatables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>